version: "3"
containers:
- name: workstation
  image: ubuntu
  shell: /bin/bash
  memory: 1024
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
aws_accounts:
- name: awsaccount
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
