version: "3"
virtualmachines:
- name: server-a
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  machine_type: n1-standard-1
- name: worker-a-1
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server-a
  machine_type: n1-standard-1
- name: worker-a-2
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server-a
  machine_type: n1-standard-1
- name: server-b
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  machine_type: n1-standard-1
- name: worker-b-1
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server-b
  machine_type: n1-standard-1
- name: worker-b-2
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server-b
  machine_type: n1-standard-1
