#!/bin/bash
REPODIR="my-repo"

if [ ! -d $REPODIR ]; then
  echo "DIAG: There is no directory called $REPODIR."
  exit 1
fi

pushd $REPODIR

git rev-parse --is-inside-work-tree >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  echo "DIAG: There seems to be no git repository. Try initializing a new git repository."
  exit 1
fi
popd

exit 0