#!/bin/bash
set -euxo pipefail
VNC_PASSWORD=instruqt

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

# Install tightvncserver, xfce4 desktop and certbot
apt -y update
DEBIAN_FRONTEND=noninteractive apt -y install xfce4 xfce4-goodies tightvncserver certbot python3-numpy

# Download the source code for novnc
wget https://github.com/novnc/noVNC/archive/refs/tags/v1.3.0.tar.gz
tar -zxvf v1.3.0.tar.gz

# Clone websockify
cd /root/noVNC-1.3.0/utils
git clone https://github.com/novnc/websockify

# Get a LetsEncrypt certificate for VNC to use
certbot certonly --standalone --preferred-challenges http -d ${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io --non-interactive --agree-tos -m trackbot@instruqt.com

# The certs have to be in *both* the websockify and root directory for this to work!
cp /etc/letsencrypt/live/${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io/cert.pem /root/self.crt
cp /etc/letsencrypt/live/${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io/privkey.pem /root/self.key
cp /root/self.crt /root/noVNC-1.3.0/utils/websockify/self.crt
cp /root/self.key /root/noVNC-1.3.0/utils/websockify/self.key

# Configure the VNC password and start novnc
mkdir /root/.vnc
echo $VNC_PASSWORD | vncpasswd -f > /root/.vnc/passwd
chmod 0600 /root/.vnc/passwd
vncserver :1

# Create a startup script for NoVNC
echo "Creating manual noVNC startup script."
cat >> /root/start_novnc.sh <<-EOF
  #!/bin/bash
  /root/noVNC-1.3.0/utils/novnc_proxy --vnc ${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io:5901 --key self.key --cert self.crt --ssl-only --listen 8443
EOF
chmod +x /root/start_novnc.sh