#!/bin/bash
# Choose your zone and cluster name
ZONE="us-central1-a"
CLUSTERNAME="instruqt-cluster"

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

# First we update the apt package manager cache
apt -y update

# Then we install some packages in noninteractive mode
DEBIAN_FRONTEND=noninteractive apt -y install curl wget htop jq vim git apt-transport-https ca-certificates gnupg python3

# Use the gcloud installation process described in the docs:
# https://cloud.google.com/sdk/docs/install#deb
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

# Configure the Helm repository
curl https://baltocdn.com/helm/signing.asc | apt-key add -
echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list

# Update apt again and install gcloud, kubectl and helm
apt -y update
apt -y install helm kubectl google-cloud-sdk-gke-gcloud-auth-plugin

# We have to install this way because the Debian APT package throws too many warnings and deprecation errors
# It appears to be out of date.
wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-387.0.0-linux-x86_64.tar.gz
tar -zxf google-cloud-cli-387.0.0-linux-x86_64.tar.gz
./google-cloud-sdk/install.sh --rc-path /root/.bashrc --command-completion true --path-update true --quiet
echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> /root/.bashrc
source /root/.bashrc

# Fetch our Google Service Account credentials
mkdir -p /root/.config/gcloud
echo $INSTRUQT_GCP_PROJECT_GCPPROJECT_SERVICE_ACCOUNT_KEY | base64 -d > /root/.config/gcloud/credentials

# Activate the service account
gcloud auth activate-service-account --key-file /root/.config/gcloud/credentials

# Set our project
gcloud config set project $INSTRUQT_GCP_PROJECT_GCPPROJECT_PROJECT_ID

# Create the GKE cluster
gcloud container clusters create $CLUSTERNAME --num-nodes=3 --zone $ZONE

# Get credentials for our cluster
gcloud container clusters get-credentials $CLUSTERNAME --zone $ZONE
