name: 'Instruqt Track Create Dev'
description: 'Converts track to a dev version for testing.'
inputs:
  path:
    description: Path to the Instruqt track.
    required: true
runs:
  using: 'composite'
  steps:
  - name: Run convert to dev
    shell: bash
    run: |
      cd ${{ inputs.path }}

      USAGE="Usage: Run script from inside an Instruqt track directory."

      # Must be in a track directory.
      if ! [[ -f track.yml ]]; then
        echo $USAGE
      fi

      # Check whether this is already a dev version track
      ISDEV=$(yq '.slug | contains("-dev")' track.yml)
      if [[ $ISDEV == "true" ]]; then
        echo -e "It looks like the track slug already has the -dev suffix.\nRun the promote-track-changes.sh script when you are done editing."
        exit 1
      fi

      # Check for the yq command
      if ! command -v yq &> /dev/null
      then
        echo "The yq command could not be found."
        exit 1
      fi

      # Strip out the track ids and rename the dev track
      echo "Converting track to dev version..."
      for file in $(find . -name assignment.md); do
        yq eval --inplace --front-matter=process 'del(.id)' $file
      done
      yq eval --inplace 'del(.id)' track.yml
      yq eval --inplace '.slug += "-dev"' track.yml
      yq eval --inplace '.title = "DEV - " + .title' track.yml

      echo "Tracks have been converted to dev versions for testing."