version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
virtualmachines:
- name: windows
  image: instruqt/windows-server
  machine_type: n1-standard-4
- name: workstation
  image: ubuntu-os-cloud/ubuntu-2004-lts
  shell: /bin/bash
  machine_type: n1-standard-1
azure_subscriptions:
- name: azsubscription
  roles:
  - Contributor
