name: 'Instruqt Track Promote'
description: 'Prepares track for validate, push and test.'
inputs:
  path:
    description: Path to the Instruqt track.
    required: true
  id:
    description: ID of the track. You should store this in a track-slugs.yml file.
    required: true
runs:
  using: 'composite'
  steps:
  - name: Inject track id and prepare for push
    shell: bash
    run: |
      cd ${{ inputs.path }}

      USAGE="Usage: Run script from inside an Instruqt track directory."

      # Must be in a track directory.
      if ! [[ -f track.yml ]]; then
        echo $USAGE
      fi

      # Check whether this is already a dev version track
      ISDEV=$(yq '.slug | contains("-dev")' track.yml)
      if [[ $ISDEV == "true" ]]; then
        echo -e "It looks like the track slug already has the -dev suffix.\nRun the promote-track-changes.sh script when you are done editing."
        exit 1
      fi

      # Check for the yq command
      if ! command -v yq &> /dev/null
      then
        echo "The yq command could not be found."
        exit 1
      fi

      # Remove the dev suffix and title prefix if they exist
      yq eval --inplace '.slug |= sub("-dev", "")' track.yml
      yq eval --inplace '.title |= sub("DEV - ", "")' track.yml

      # Strip ids from assignment.md files
      for file in $(find . -name assignment.md); do
        yq eval --inplace --front-matter=process 'del(.id)' $file
      done

      # Remove id from track.yml file if it exists
      yq eval --inplace 'del(.id)' track.yml

      # Inject the correct id back into the file
      yq eval --inplace '.id = "${{ inputs.id }}"' track.yml